#available_text_models: ["gpt-3.5-turbo", "gpt-3.5-turbo-16k", "gpt-4-1106-preview", "gpt-4", "text-davinci-003"]
available_text_models: ["gpt-4o-mini", "gpt-4o"]
info:
  gpt-3.5-turbo:
    type: chat_completion
    name: ChatGPT
    description: ChatGPT - это известная модель. Она <b>быстрая</b> и <b>доступная</b>. Идеальна для повседневных задач. Если есть задачи, с которыми она не справляется, попробуйте <b>GPT-4</b>.

    price_per_1000_input_tokens: 0.0015
    price_per_1000_output_tokens: 0.002

    scores:
      Умный: 3
      Быстрый: 5
      Дешевый: 5

  gpt-3.5-turbo-16k:
    type: chat_completion
    name: GPT-16K
    description: GPT-16K - это известная модель. Она <b>быстрая</b> но <b>дороже</b>. Имеет окно контекста в 16 тысяч символов.

    price_per_1000_input_tokens: 0.003
    price_per_1000_output_tokens: 0.004

    scores:
      Умный: 3
      Быстрый: 5
      Дешевый: 4

  gpt-4o:
    type: chat_completion
    name: GPT-4o
    description: GPT-4o - это <b>самая умная</b> и передовая модель в мире. Она <b>быстрая</b> и <b>недорогая</b>. Идеальна для <b>сложных</b> интеллектуальных задач.

    price_per_1000_input_tokens: 0.015
    price_per_1000_output_tokens: 0.03

    scores:
      Умный: 5
      Быстрый: 5
      Дешевый: 3

  gpt-4o-mini:
    type: chat_completion
    name: GPT-4o Mini
    description: GPT-4o Mini - это облегченная версия GPT-4o. Она <b>быстрее</b> и <b>дешевле</b>, но немного уступает в возможностях полной версии.

    price_per_1000_input_tokens: 0.0001
    price_per_1000_output_tokens: 0.0002

    scores:
      Умный: 4
      Быстрый: 5
      Дешевый: 5

  gpt-4-1106-preview:
    type: chat_completion
    name: GPT-4 Turbo
    description: GPT-4 Turbo более <b>быстрая</b> и <b>дешевая</b> версия GPT-4. Он не уступает GPT-4, поэтому его следует использовать вместо GPT-4.

    price_per_1000_input_tokens: 0.01
    price_per_1000_output_tokens: 0.03

    scores:
      Умный: 5
      Быстрый: 4
      Дешевый: 3


  gpt-4-vision-preview:
    type: chat_completion
    name: GPT-4 Vision
    description: Ability to <b>understand images</b>, in addition to all other GPT-4 Turbo capabilties.

    price_per_1000_input_tokens: 0.01
    price_per_1000_output_tokens: 0.03

    scores:
      smart: 5
      fast: 4
      cheap: 3
  gpt-4o:
    type: chat_completion
    name: GPT-4o
    description: GPT-4o is a special variant of GPT-4 designed for optimal performance and accuracy. Suitable for complex and detailed tasks.

    price_per_1000_input_tokens: 0.03
    price_per_1000_output_tokens: 0.06

    scores:
      smart: 5
      fast: 2
      cheap: 2

  gpt-4-vision-preview:
    type: chat_completion
    name: GPT-4 Vision
    description: Ability to <b>understand images</b>, in addition to all other GPT-4 Turbo capabilties.

    price_per_1000_input_tokens: 0.01
    price_per_1000_output_tokens: 0.03

    scores:
      smart: 5
      fast: 4
      cheap: 3
  gpt-4o:
    type: chat_completion
    name: GPT-4o
    description: GPT-4o is a special variant of GPT-4 designed for optimal performance and accuracy. Suitable for complex and detailed tasks.

    price_per_1000_input_tokens: 0.03
    price_per_1000_output_tokens: 0.06

    scores:
      smart: 5
      fast: 2
      cheap: 2

  text-davinci-003:
    type: completion
    name: GPT-3.5
    description: GPT-3.5 - это устаревшая модель. На самом деле <b>нет причины использовать её</b>, потому что она дороже и медленнее, чем ChatGPT, но примерно также умна.

    price_per_1000_input_tokens: 0.02
    price_per_1000_output_tokens: 0.02

    scores:
      Умный: 3
      Быстрый: 2
      Дешевый: 3

  dalle-2:
     type: image
     price_per_1_image: 0.018  # 512x512

  whisper:
    type: audio
    price_per_1_min: 0.006
